### ISSUE TITLE
Did DataStax force TLP to stop working on these projects?

### ISSUE THREAD

**Issue by pdehlke** [thelastpickle/tlp-stress#138]
Other than reaper (and I'm guessing that will die some day, too) it looks like TLP folks haven't committed to these projects since September of 2020.

There are multiple outstanding requests for changes to documentation and installers that reference the now dead bintray.com, and nobody is even bothering to respond.

DataStax is a pox on the open source cassandra community. Start mirroring https://thelastpickle.com/blog/ now before it, too, gets buried :(

**Comment by ossarga** [comment]
Hi @pdehlke,

The short answer to your question is, no.

I will try to find sometime, in the next two weeks to update the documentation and links to the installers.

Since TLP has joined DataStax, no one has been forced to stop working on any TLP open source projects. Please be assured that Reaper, Medusa, TLP Cluster, TLP Stress, and the TLP blog post are all alive and well. DataStax's position is to help, support, and grow the Cassandra community. One of the ways we do that is through the TLP resources and projects acquired.

Those of us in the DataStax services team have been incredibly busy with other priorities at the moment. I am very sorry that work on some of the tooling has slowed down. Some ex-TLP folks are part of  the engineering team and are actively working on a number of TLP tools. In particular, Reaper and Medusa are both core components packaged in the [K8ssandra ecosystem](https://k8ssandra.io/about/). Both are actively being worked on by the engineering team.

TLP Cluster is being worked on by myself and @adejanovski. We have a branch open with some major features on their way. Unfortunately, as I mentioned earlier finding the time to work on it has been difficult.

TLP Stress is still being maintained. Whilst it is a very easy to use stress tool, DataStax also provides NoSQL bench which is an open source stress tool as well. NoSQL bench existed internally before TLP Stress and is actively worked on. NoSQL bench is a more advanced stress tool and we feel there is less urgency in enhancing the TLP Stress features. Given it has a large following, we will still maintain it and accept pull requests for new features/fixes.

TLP Blog posts are actively being created by us. DataStax considers the blog as a very valuable resource for the Apache Cassandra community. As such. we will definitely continue to post high quality and useful information about and relating to Apache Cassandra.
