### ISSUE TITLE
Coordinated omission in latency measurements

### ISSUE THREAD

**Issue by nitsanw** [thelastpickle/tlp-stress#49]
TLP stress does not have a notion of scripted start time and is thus subject to coordinated omission. This is an issue that has been fixed for other load generators like YCSB and cassandra-stress.

**Comment by rustyrazorblade** [comment]
Without something actionable I'm not sure what you want me to to, closing this out.  Feel free to reopen if you have a suggestion.

**Comment by nitsanw** [comment]
I'm sorry if the description seems too abrupt, perhaps the intent is unclear, I'll try again.
Coordinated omission is pretty well established term for a particular measurement issue where the load generator effectively coordinates with the system under test to produce skewed results. A good explanation is here : https://www.youtube.com/watch?v=lJ8ydIuPFeU

I fixed this issue for YCSB and cassandra stress. The fixes are detailed in these blog posts:
http://psy-lob-saw.blogspot.com/2015/03/fixing-ycsb-coordinated-omission.html
http://psy-lob-saw.blogspot.com/2016/07/fixing-co-in-cstress.html

The fix for this load generator will be around this point in the code:
https://github.com/thelastpickle/tlp-stress/blob/90e245d019de8302db6873548479871538c83f75/src/main/kotlin/com/thelastpickle/tlpstress/ProfileRunner.kt#L101

The rate limiter should be returning the expected start time when a given pace of execution is desirable, or at least that is the best way I know to fix this issue.
I hope this is enough detail, happy to discuss further.

**Comment by rustyrazorblade** [comment]
I think there's a bit of confusion around how tlp-stress works, so let me explain.

First off, that rate limiter will almost never be used.  It was added because we were doing some tests with CCM and tlp-stress was overwhelming the test cluster.  The rate limiter is only there as an optional safeguard to prevent people's laptops from locking up when using tlp-stress :)

tlp-stress doesn't try to meet some target number of operations.  Rather, it pushes as many queries per second as possible, limited only by the number of concurrent queries in flight.  As soon as a query returns, another starts.    In other words, there is no schedule we're attempting to adhere to (yes I read the posts), so there's no time that a request spends in a queue.
